/**
 * @file control.c
 * @brief Flight Control Output Implementation for ESP32-C3 Flight Controller
 * 
 * This module handles PWM output control using the ESP32-C3 LEDC peripheral.
 * Provides thread-safe control surface updates with failsafe handling.
 */

#include "control.h"
#include "config.h"
#include "xm_plus.h"
#include "sbus.h"


#include <string.h>

#include <stdio.h>
#include "driver/ledc.h"
#include "driver/gpio.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

static const char *TAG = "control";

// Static state for control system
static control_outputs_t s_outputs = {0};
static SemaphoreHandle_t s_control_mutex = NULL;
static bool s_armed = true;
static bool s_initialized = false;
static bool s_failsafe_active = false;

// Convert control us range [0..1000] directly to PWM microseconds
// Pins are generated by LEDC at PWM_FREQ_HZ; LEDC duty is derived from us.
static inline uint16_t clamp_u16(uint16_t v, uint16_t lo, uint16_t hi)
{
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

static uint16_t control_us_to_pwm_us(uint16_t us01)
{
    // Requirement: throttle/roll/pitch/yaw are set as PWM microseconds directly (0..1000)
    // and center=500.
    return clamp_u16(us01, 0, 1000);
}


// Queue for passing SBUS decoded frames from main/xm_plus into control task
static QueueHandle_t s_xm_queue = NULL;
static TaskHandle_t s_control_task_handle = NULL;

typedef struct {
    xm_plus_data_t data;
} control_queue_item_t;

#define CONTROL_XM_QUEUE_LEN  3

static void control_apply_from_xm(const xm_plus_data_t *xm);


// LEDC channel assignments
// Use extra LEDC channels so we can drive CH1/CH2/CH4 on GPIO1/2/0.
#define LEDC_CHANNEL_MOTOR    LEDC_CHANNEL_2  // CH3 -> GPIO10 (existing)
#define LEDC_CHANNEL_CH1      LEDC_CHANNEL_1  // CH1 -> GPIO1
#define LEDC_CHANNEL_CH2      LEDC_CHANNEL_0  // CH2 -> GPIO2
#define LEDC_CHANNEL_CH4      LEDC_CHANNEL_3  // CH4 -> GPIO0

// Keep legacy names mapped to the same LEDC channels to avoid touching control.h/public API.
#define LEDC_CHANNEL_SERVO_L LEDC_CHANNEL_CH1
#define LEDC_CHANNEL_SERVO_R LEDC_CHANNEL_CH2


/**
 * @brief Convert pulse width in microseconds to LEDC duty cycle value
 * 
 * @param us Pulse width in microseconds (1000-2000)
 * @return LEDC duty cycle value
 */
static uint32_t us_to_duty(uint16_t us)
{
    // PWM period in microseconds (50Hz = 20000us)
    const uint32_t period_us = 1000000 / PWM_FREQ_HZ;
    
    // Calculate duty cycle
    uint32_t duty = ((uint32_t)us * PWM_DUTY_MAX) / period_us;
    
    // Clamp to valid range
    if (duty > PWM_DUTY_MAX) {
        duty = PWM_DUTY_MAX;
    }
    
    return duty;
}

/**
 * @brief Map SBUS channel value to pulse width in microseconds
 * 
 * SBUS values range from 172 to 1811 (FrSky standard)
 * Maps to 1000-2000 microseconds PWM pulse width
 * 
 * @param sbus_value SBUS channel value (172-1811)
 * @return Pulse width in microseconds (1000-2000)
 */
// Convert SBUS (172..1811) -> control units (0..1000), where center ~= 500.
static uint16_t sbus_to_0_1000(uint16_t sbus_value)
{
    const uint16_t sbus_min = 172;
    const uint16_t sbus_max = 1811;

    sbus_value = clamp_u16(sbus_value, sbus_min, sbus_max);

    // Map linearly: [172..1811] => [0..1000]
    return (uint16_t)(((uint32_t)(sbus_value - sbus_min) * 1000U) / (uint32_t)(sbus_max - sbus_min));
}


/**
 * @brief Set PWM output for a specific LEDC channel
 * 
 * @param channel LEDC channel number
 * @param us Pulse width in microseconds
 */
static void set_pwm_channel(ledc_channel_t channel, uint16_t us)
{
    uint32_t duty = us_to_duty(us);
    ledc_set_duty(LEDC_LOW_SPEED_MODE, channel, duty);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, channel);
}

/**
 * @brief Apply current control outputs to hardware
 * 
 * Updates all PWM channels and GPIO outputs based on s_outputs.
 * Must be called with mutex held.
 */
static void apply_outputs(void)
{
    // Apply PWM outputs
    if (s_armed) {
        // throttle_us is already in PWM-microseconds units (0..1000)
        // and LEDC duty is derived from it by us_to_duty()
        set_pwm_channel(LEDC_CHANNEL_MOTOR, s_outputs.throttle_us);
    } else {
        // When disarmed, throttle cut
        set_pwm_channel(LEDC_CHANNEL_MOTOR, 0);
    }

    // roll/pitch/yaw are each driven on dedicated GPIO via LEDC channels
    set_pwm_channel(LEDC_CHANNEL_CH1, s_outputs.roll_us);
    set_pwm_channel(LEDC_CHANNEL_CH2, s_outputs.pitch_us);
    set_pwm_channel(LEDC_CHANNEL_CH4, s_outputs.yaw_us);

    // Apply LED outputs
    gpio_set_level(PIN_LED1, s_outputs.led1_state ? 1 : 0);
    gpio_set_level(PIN_LED2, s_outputs.led2_state ? 1 : 0);
}

// Called when RX is valid again; clears failsafe lockout so control_update_from_sbus can drive outputs.
static void control_on_rx_reconnected(void)
{
    // If the receiver was in failsafe lock, release it when new valid frames arrive.
    s_failsafe_active = false;

    // Keep arming policy: only motor output depends on s_armed.
    // If it was forced disarmed during failsafe, re-arm by default.
    if (!s_armed) {
        s_armed = true;
        // Leave attitude as-is; throttle will be controlled by SBUS update next.
        // (Safety: throttle_us will be derived from CH3 in control_update_from_sbus.)
    }
}



bool control_init(void)
{
    if (s_initialized) {
        ESP_LOGW(TAG, "Already initialized");
        return true;
    }

    // NOTE: legacy queue/task code was disabled; it must not affect preprocessing.


    
    ESP_LOGI(TAG, "Initializing control system");
    
    // Create mutex for thread-safe access
    s_control_mutex = xSemaphoreCreateMutex();
    if (s_control_mutex == NULL) {
        ESP_LOGE(TAG, "Failed to create mutex");
        return false;
    }
    
    // Initialize LEDC timer
    ledc_timer_config_t timer_conf = {
        .duty_resolution = PWM_RES_BITS,
        .freq_hz = PWM_FREQ_HZ,
        .speed_mode = LEDC_LOW_SPEED_MODE,
        .timer_num = LEDC_TIMER_0,
        .clk_cfg = LEDC_AUTO_CLK,
        .deconfigure = false,
    };
    
    esp_err_t err = ledc_timer_config(&timer_conf);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_timer_config failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }
    
    // Configure LEDC channels for motor and servos
    ledc_channel_config_t channel_conf = {
        .channel = 0,
        .duty = 0,
        .gpio_num = PIN_PWM_MOTOR,
        .speed_mode = LEDC_LOW_SPEED_MODE,
        .hpoint = 0,
        .timer_sel = LEDC_TIMER_0,
        .flags.output_invert = 0,
    };
    
    // Motor channel
    channel_conf.channel = LEDC_CHANNEL_MOTOR;
    channel_conf.gpio_num = PIN_PWM_MOTOR;
    err = ledc_channel_config(&channel_conf);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_channel_config (motor) failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }
    
// CH1 channel (SBUS ch0) -> GPIO1
    channel_conf.channel = LEDC_CHANNEL_CH1;
    channel_conf.gpio_num = PIN_PWM_SERVO_L; // GPIO1
    err = ledc_channel_config(&channel_conf);

    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_channel_config (servo_l) failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }
    
// CH2 channel (SBUS ch1) -> GPIO2
    channel_conf.channel = LEDC_CHANNEL_CH2;
    channel_conf.gpio_num = PIN_PWM_SERVO_L + 1; // GPIO2
    err = ledc_channel_config(&channel_conf);

    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_channel_config (servo_r) failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }
    
    // CH4 channel (SBUS ch3) -> GPIO0
    channel_conf.channel = LEDC_CHANNEL_CH4;
    channel_conf.gpio_num = PIN_PWM_SERVO_R; // GPIO0
    err = ledc_channel_config(&channel_conf);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_channel_config (ch4) failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }

    // Configure GPIO for LEDs
    gpio_config_t io_conf = {
        .pin_bit_mask = (1ULL << PIN_LED1) | (1ULL << PIN_LED2),

        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE,
    };
    
    err = gpio_config(&io_conf);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "gpio_config failed: %d", err);
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
        return false;
    }
    
    // Initialize outputs to safe state
    s_outputs.throttle_us = 0;
    s_outputs.roll_us = 500;
    s_outputs.pitch_us = 500;
    s_outputs.yaw_us = 500;
    s_outputs.led1_state = false;
    s_outputs.led2_state = false;
    s_armed = true;
    s_failsafe_active = false;

    
    // Apply safe initial state
    apply_outputs();
    
    s_initialized = true;
    // ESP_LOGI(TAG, "Control initialized: motor=%d servoL=%d servoR=%d LED1=%d LED2=%d",
    //          PIN_PWM_MOTOR, PIN_PWM_SERVO_L, PIN_PWM_SERVO_R, PIN_LED1, PIN_LED2);
    
    return true;
}

void control_update_from_sbus(const uint16_t channels[16])
{
    if (channels == NULL || !s_initialized) {
        return;
    }
    
    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        // Check for failsafe lockout
        if (s_failsafe_active) {
            // If we have new SBUS channels, treat it as reconnect and release failsafe lock.
            control_on_rx_reconnected();
        }

        if (s_failsafe_active) {
            xSemaphoreGive(s_control_mutex);
            return;
        }

        
        // Map SBUS channels to control outputs
        
        // Motor/dimmer brightness from CH3 (index 2)
        // Map SBUS 172..1811 -> duty 0..100%
        uint16_t raw = channels[2];
        if (raw < 172) raw = 172;
        if (raw > 1811) raw = 1811;
        uint32_t percent = (uint32_t)(raw - 172) * 100U / (uint32_t)(1811 - 172);

        // Convert percent -> microseconds 0..1000, then to duty via LEDC mapping
        uint16_t dim_us = (uint16_t)((percent * 1000U) / 100U); // 0..1000us

        // Use motor_us field as dimmer pulse for GPIO10
        // If disarmed, force 0%
        
        if (!s_armed) {
            dim_us = 0;
        }
        s_outputs.throttle_us = dim_us;

        // Debug log: PWM us values per output
        // GPIO10 is driven by motor_us currently.
        // GPIO0/1/2 are driven by servo_l_us/servo_r_us + (legacy fields) depending on wiring.
        // For this mapping update:
        //   GPIO0  <- CH4
        //   GPIO1  <- CH1
        //   GPIO2  <- CH2
        // We still compute CH1/CH2 mixing into servo_l_us/servo_r_us, so treat:
        //   GPIO1/2 from servo_l_us/servo_r_us, and
        //   GPIO0 from servo_r_us (temporary) until CH4 mixing is implemented.
        ESP_LOGI(TAG, "PWM debug: GPIO10:%u GPIO0:%u GPIO1:%u GPIO2:%u (armed=%d)",
                 (unsigned)s_outputs.throttle_us,
                 (unsigned)s_outputs.yaw_us,
                 (unsigned)s_outputs.roll_us,
                 (unsigned)s_outputs.pitch_us,
                 (int)s_armed);



        // Map 4 channels directly into roll/pitch/yaw/throttle control units (0..1000)
        // Requirement: throttle/roll/pitch/yaw are PWM microseconds directly.

        s_outputs.roll_us  = sbus_to_0_1000(channels[SBUS_CH_AILERON]);
        s_outputs.pitch_us = sbus_to_0_1000(channels[SBUS_CH_ELEVATOR]);
        s_outputs.yaw_us   = sbus_to_0_1000(channels[SBUS_CH_RUDDER]);

        // LED outputs from AUX switches
        s_outputs.led1_state = channels[SBUS_CH_AUX1] > 1500;
        s_outputs.led2_state = channels[SBUS_CH_AUX2] > 1500;
        
        // Check for arming command (typically throttle stick down-right)
        // This is a simple implementation - can be enhanced
        if (!s_armed && channels[SBUS_CH_THROTTLE] < 200 && 
            channels[SBUS_CH_RUDDER] > 1700) {
            control_arm();
        } else if (s_armed && channels[SBUS_CH_THROTTLE] < 200 && 
                   channels[SBUS_CH_RUDDER] < 300) {
            control_disarm();
        }
        
        apply_outputs();
        xSemaphoreGive(s_control_mutex);
    }
}

void control_set_outputs(const control_outputs_t *outputs)
{
    if (outputs == NULL || !s_initialized) {
        return;
    }

    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        // throttle_us is in PWM microseconds units [0..1000]
        s_outputs.throttle_us = outputs->throttle_us;
        s_outputs.roll_us     = outputs->roll_us;
        s_outputs.pitch_us    = outputs->pitch_us;
        s_outputs.yaw_us      = outputs->yaw_us;

        // Clamp to required ranges
        s_outputs.throttle_us = clamp_u16(s_outputs.throttle_us, 0, 1000);
        s_outputs.roll_us     = clamp_u16(s_outputs.roll_us, 0, 1000);
        s_outputs.pitch_us    = clamp_u16(s_outputs.pitch_us, 0, 1000);
        s_outputs.yaw_us      = clamp_u16(s_outputs.yaw_us, 0, 1000);

        s_outputs.led1_state = outputs->led1_state;
        s_outputs.led2_state = outputs->led2_state;

        // When disarmed, enforce throttle cut and center attitude
        if (!s_armed) {
            s_outputs.throttle_us = 0;
            s_outputs.roll_us = 500;
            s_outputs.pitch_us = 500;
            s_outputs.yaw_us = 500;
        }

        apply_outputs();
        xSemaphoreGive(s_control_mutex);
    }
}


void control_get_outputs(control_outputs_t *outputs)
{
    if (outputs == NULL || !s_initialized) {
        return;
    }
    
    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        memcpy(outputs, &s_outputs, sizeof(control_outputs_t));
        xSemaphoreGive(s_control_mutex);
    }
}

void control_arm(void)
{
    if (!s_initialized) return;
    
    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        if (!s_armed) {
            s_armed = true;
            s_failsafe_active = false;
            // When arming: keep attitude centered, throttle=0 until stick input
            s_outputs.throttle_us = 0;
            s_outputs.roll_us = 500;
            s_outputs.pitch_us = 500;
            s_outputs.yaw_us = 500;
            apply_outputs();
            ESP_LOGI(TAG, "System ARMED");
        }
        xSemaphoreGive(s_control_mutex);
    }
}


void control_disarm(void)
{
    if (!s_initialized) return;
    
    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        if (s_armed) {
            s_armed = false;
            s_outputs.throttle_us = 0;
            apply_outputs();
            ESP_LOGI(TAG, "System DISARMED");
        }
        xSemaphoreGive(s_control_mutex);
    }
}

bool control_is_armed(void)
{
    bool armed = false;
    if (s_initialized && s_control_mutex != NULL) {
        if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
            armed = s_armed;
            xSemaphoreGive(s_control_mutex);
        }
    }
    return armed;
}

void control_failsafe(void)
{
    if (!s_initialized) return;
    
    if (xSemaphoreTake(s_control_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {
        s_failsafe_active = true;
        s_armed = false;
        // Keep attitude (roll/pitch/yaw) at last known values.
        // This prevents outputs from freezing centered after a brief RX glitch.
        // Only throttle will be cut.
        s_outputs.roll_us = s_outputs.roll_us;
        s_outputs.pitch_us = s_outputs.pitch_us;
        s_outputs.yaw_us = s_outputs.yaw_us;
        
        // Failsafe policy:
        // - throttle_us = 0 (cut motor)
        // - keep roll/pitch/yaw at last known values (do not hard-center)
        // - LEDs on
        s_outputs.throttle_us = 0;
        s_outputs.led1_state = true;
        s_outputs.led2_state = true;

        apply_outputs();
        ESP_LOGW(TAG, "FAILSAFE activated - throttle=0, attitude centered");
        
        xSemaphoreGive(s_control_mutex);
    }
}

void control_deinit(void)
{
    // Stop task/queue first (if running)
    if (s_control_task_handle != NULL) {
        vTaskDelete(s_control_task_handle);
        s_control_task_handle = NULL;
    }
    if (s_xm_queue != NULL) {
        vQueueDelete(s_xm_queue);
        s_xm_queue = NULL;
    }

    if (!s_initialized) {
        return;
    }

    
    // Set all outputs to safe state
    set_pwm_channel(LEDC_CHANNEL_MOTOR, ESC_MIN_US);
    set_pwm_channel(LEDC_CHANNEL_SERVO_L, SERVO_CENTER_US);
    set_pwm_channel(LEDC_CHANNEL_SERVO_R, SERVO_CENTER_US);
    gpio_set_level(PIN_LED1, 0);
    gpio_set_level(PIN_LED2, 0);
    
    // Reset state
    s_armed = false;
    s_failsafe_active = false;
    memset(&s_outputs, 0, sizeof(s_outputs));
    s_initialized = false;
    
    // Delete mutex
    if (s_control_mutex != NULL) {
        vSemaphoreDelete(s_control_mutex);
        s_control_mutex = NULL;
    }
    
ESP_LOGI(TAG, "Control system deinitialized");
}

// ===== Queue/Task based control (removed for compatibility) =====

#if 0
static void control_apply_from_xm(const xm_plus_data_t *xm)
{

    if (xm == NULL) return;

    if (!xm->data_valid) {
        if (control_is_armed()) {
            control_failsafe();
        }
        return;
    }

    if (xm->flags & 0x08) {
        if (control_is_armed()) {
            control_failsafe();
        }
        return;
    }

    // Normal operation: reuse legacy mapping logic by building channel array on stack.
    // The control_update_from_sbus() expects channels[16].
    control_update_from_sbus(xm->channels);
}

bool control_enqueue_xm(const xm_plus_data_t *data)
{
    if (data == NULL) return false;
    if (s_xm_queue == NULL) return false;

    control_queue_item_t item;
    memcpy(&item.data, data, sizeof(xm_plus_data_t));

    // overwrite oldest by draining if queue is full
    if (uxQueueSpacesAvailable(s_xm_queue) == 0) {
        control_queue_item_t dummy;
        xQueueReceive(s_xm_queue, &dummy, 0);
    }

    return (xQueueSend(s_xm_queue, &item, 0) == pdTRUE);
}

static void control_task(void *arg)
{
    (void)arg;

    ESP_LOGI(TAG, "control_task started");

    control_queue_item_t newest;
    control_queue_item_t tmp;

    while (1) {
        // Block until at least one item is available.
        if (xQueueReceive(s_xm_queue, &newest, portMAX_DELAY) != pdTRUE) {
            continue;
        }

        // Drain to the latest item so we don't lag behind.
        while (xQueueReceive(s_xm_queue, &tmp, 0) == pdTRUE) {
            newest = tmp;
        }

        // Apply latest
        control_apply_from_xm(&newest.data);

        vTaskDelay(1);
    }
}

bool control_start_task(void)
{

    if (!s_initialized) return false;
    if (s_xm_queue != NULL) return true;

    s_xm_queue = xQueueCreate(CONTROL_XM_QUEUE_LEN, sizeof(control_queue_item_t));

    if (s_xm_queue == NULL) {
        ESP_LOGE(TAG, "Failed to create control XM queue");
        return false;
    }

    BaseType_t ok = xTaskCreate(control_task, "control_task", 4096, NULL, configMAX_PRIORITIES - 3, &s_control_task_handle);
    if (ok != pdPASS) {
        ESP_LOGE(TAG, "Failed to create control_task");
        vQueueDelete(s_xm_queue);
        s_xm_queue = NULL;
        s_control_task_handle = NULL;
        return false;
    }

    return true;
}

#endif // #if 0


